---
# postfix_relay_client/tasks/main.yml

- name: install postfix
  package:
    name:
      - postfix
      - mailx
    state: present

# - name: setup root alias
#   lineinfile:
#     path: /etc/aliases
#     regexp: '^root:'
#     line: 'root: root@sleif.de'
#   notify: reload_postfix

- name: run postfix configuration (without backrefs)
  lineinfile:
    dest: /etc/postfix/main.cf
    backup: True
    backrefs: False
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  with_items:
    - { line: 'myorigin = {{ postfix_relay_client_relayhost_myorigin }}', regexp: '^myorigin.*$' }
    - { line: 'relayhost = [{{ postfix_relay_client_relayhost }}]:{{ postfix_relay_client_relayhost_port }}', regexp: '^relayhost.*$' }
    - { line: 'mydestination = ', regexp: '^mydestination.*$' }
  notify: reload_postfix

- name: run postfix configuration (with backrefs)
  lineinfile:
    dest: /etc/postfix/main.cf
    backup: True
    backrefs: True
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  with_items:
    - { line: '\1 127.0.0.0/8', regexp: '(^mynetworks =([\"\s]+(?!127\.0\.0\.0\/8)[\w=\[\]\:\/\-\.]+)*)\s*$' }
    - { line: '\1 [::ffff:127.0.0.0]/104', regexp: '(^mynetworks =([\"\s]+(?!\[\:\:ffff\:127\.0\.0\.0\]\/104)[\w=\[\]\:\/\-\.]+)*)\s*$' }
    - { line: '\1 [::1]/128', regexp: '(^mynetworks =([\"\s]+(?!\[\:\:1\]\/128)[\w=\[\]\:\/\-\.]+)*)\s*$' }
  notify: reload_postfix

- name: do sasl configuration for smtp with authentication
  block:
    - name: install cyrus-sasl libs
      package:
        name: cyrus-sasl-plain

    - name: define pw for postfix remote relay
      lineinfile:
        create: yes
        path: /etc/postfix/sasl_passwd
        regexp: '^{{ postfix_relay_client_relayhost }}.*'
        line: '{{ postfix_relay_client_relayhost }} {{ postfix_relay_client_relayhost_user }}:{{ postfix_relay_client_relayhost_password }}'
        owner: root
        group: root
        mode: '600'
      notify: postmap_sasl_password

    - name: define tls policy for relay server
      lineinfile:
        create: yes
        path: /etc/postfix/tls_policy
        regexp: '^\[{{ postfix_relay_client_relayhost }}\].*'
        line: '[{{ postfix_relay_client_relayhost }}]:{{ postfix_relay_client_relayhost_port }} encrypt'
        owner: root
        group: root
        mode: '600'
      notify: postmap_tls_policy

    - name: run postfix configuration (without backrefs)
      lineinfile:
        dest: /etc/postfix/main.cf
        backup: True
        backrefs: False
        line: "{{ item.line }}"
        regexp: "{{ item.regexp }}"
      with_items:
        - { line: 'smtp_use_tls = yes', regexp: '^smtp_use_tls.*$' }
        - { line: 'smtp_sasl_auth_enable = yes', regexp: '^smtp_sasl_auth_enable.*$' }
        - { line: 'smtp_sasl_security_options = noanonymous', regexp: '^smtp_sasl_security_options.*$' }
        - { line: 'smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd', regexp: '^smtp_sasl_password_maps.*$' }
      notify: reload_postfix

  when: postfix_relay_client_relayhost_user | length > 0

- name: enable and start postfix service
  service:
    name: postfix
    state: started
    enabled: yes
