---

- name: postmap_sasl_password
  command: /usr/sbin/postmap /etc/postfix/sasl_passwd

- name: postmap_tls_policy
  command: /usr/sbin/postmap /etc/postfix/tls_policy

- name: reload_postfix
  service:
    name: postfix
    state: reloaded
  notify:
    - send_test_mail

- name: send_test_mail
  shell: echo "test 23" | mail -s "test23 {{ ansible_fqdn }}" root
  args:
    executable: /bin/bash
